# Generated by Django 3.0.5 on 2020-05-07 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20200419_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerTasted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beername', models.TextField()),
                ('rating', models.TextField()),
                ('style', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beerstasted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BeersTasted',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
